#

# Lecture 16 Notes

## Mayoral of Rebelton

Generate some p-values

In [24]:
import random
import pandas as pd
random.seed(17)

def generate_p_values():
    p_values = []
    count_below_5 = 0

    # Keep generating values until we have 7 below 0.05
    while count_below_5 < 7:
        p = random.uniform(0, 1)
        p_values.append(p)
        if p < 0.05:
            count_below_5 += 1

    # Sort the list in increasing order
    p_values.sort()
    
    return p_values

# Generate and display the sorted p-values
sorted_p_values = generate_p_values()

# Create a DataFrame for pretty display
df = pd.DataFrame({'p-value': sorted_p_values})

# Display the table in a Jupyter-friendly format
#import ace_tools as tools
#tools.display_dataframe_to_user(name="Sorted P-Values", dataframe=df_sorted_p_values)

#df.head(100)

df = df.iloc[0:100]
print(df.count())

from IPython.display import display
display(df.iloc[0:10])
display(df)

p-value    100
dtype: int64

    p-value
0  0.009763
1  0.012100
2  0.017834
3  0.020661
4  0.026937
5  0.028378
6  0.049443
7  0.051669
8  0.062193
9  0.075017

     p-value
0   0.009763
1   0.012100
2   0.017834
3   0.020661
4   0.026937
..       ...
95  0.633102
96  0.636503
97  0.638773
98  0.657451
99  0.658565

[100 rows x 1 columns]

In [26]:
# Number of hypotheses (total p-values)
m = len(df)

# Set FDR threshold
FDR = 0.05

# Compute alpha_i values using Benjamini-Hochberg procedure
df = df.sort_values(by='p-value')  # Ensure sorting
df['alpha (FDR 5%)'] = [(i+1)/m * FDR for i in range(m)]

# Determine significance: p-value < alpha_i (FDR threshold per rank)
#df_sorted_p_values['Significant (FDR 5%)'] = df_sorted_p_values['p-value'] < df_sorted_p_values['alpha (FDR 5%)']

display(df.iloc[0:10])
display(df)

    p-value  alpha (FDR 5%)
0  0.009763          0.0005
1  0.012100          0.0010
2  0.017834          0.0015
3  0.020661          0.0020
4  0.026937          0.0025
5  0.028378          0.0030
6  0.049443          0.0035
7  0.051669          0.0040
8  0.062193          0.0045
9  0.075017          0.0050

     p-value  alpha (FDR 5%)
0   0.009763          0.0005
1   0.012100          0.0010
2   0.017834          0.0015
3   0.020661          0.0020
4   0.026937          0.0025
..       ...             ...
95  0.633102          0.0480
96  0.636503          0.0485
97  0.638773          0.0490
98  0.657451          0.0495
99  0.658565          0.0500

[100 rows x 2 columns]

$$\alpha_1 = \bigg(\frac{i}{m}\bigg) \cdot FDR = \frac{1}{100} \cdot 0.05 = 0.0005$$